### ISSUE TITLE
Почему strip только для региона?

### ISSUE THREAD

**Issue by coursar** [sergey-lb/avito#2]
https://github.com/sergey-lb/avito/blob/324ef3f064fa1b97bde55ed4b1eb6c3a9f139eac/app/lib.py#L3

**Comment by sergey-lb** [comment]
Здесь, наверное, правильнее в функции search_apartments strip вызывать? А функция create_apartment должна заниматься только созданием сущности, без изменения
передаваемых ей данных. Проверку/обработку данных принимаемых от пользователя наверное отдельно лучше делать, до вызова create_apartment? А потом в create_apartment уже обработанные данные передавать.

**Comment by coursar** [comment]
Проверку лучше действительно отдельно.

Я спросил к тому, что у вас почему-то только регион `strip`'ается. По такой логике всех надо `strip`'ать, либо не `strip`'ать никого.

В остальном ваше мысли в комментарии все правильные
