### ISSUE TITLE
Зачем делать эту функцию вложенной?

### ISSUE THREAD

**Issue by coursar** [sergey-lb/avito#4]
https://github.com/sergey-lb/avito/blob/0dce7134dbfcbbc26ff29808211bda615c526074/app/lib.py#L27-L30

**Comment by sergey-lb** [comment]
В данном случае, чтобы проверить содержится ли квартира в списке нам нужны две переменные apartment и search_regions, а filter вызывает функцию только с одним параметром (apartment). Т.е. нам нужно, чтобы переменная search_regions была также доступна в области видимости данной функции. Это также можно решить используя lambda, partial или closure, если бы была необходимость выносить функцию на уровень выше (в глобальную область в данном случае), но, думаю, в этом нет необходимости, так как эта функция нигде больше не используется. И еще считаю, что так удобнее работать с кодом, когда функция сразу над фильтром находится, чтобы не искать ее потом в файле, когда проект разрастется. С другой стороны, если разрастется сама функция, то тогда уже лучше будет вынести ее.
