### ISSUE TITLE
Зачем теперь создавать копию при поиске?

### ISSUE THREAD

**Issue by coursar** [sergey-lb/avito#5]
https://github.com/sergey-lb/avito/blob/0dce7134dbfcbbc26ff29808211bda615c526074/app/lib.py#L21

**Comment by sergey-lb** [comment]
Да, в данном случае не надо, так как filter не меняет исходный список. Исправлено в de3318766dc9666aa3459859d64bec271d4f2594 . Также в тест соответствующую проверку добавил.
